### ISSUE TITLE
Serial Port won't open unless ports are searched for

### ISSUE THREAD

**Issue by tresf** [qzindustries/qz-print#10]
Build 1.9.9.1:  Opening a serial port will throw an exception "failed to call NPObject" if you simply try to open the port without first clicking "find ports".

**Comment by myrridin** [comment]
This is fixed by commit: https://github.com/qzindustries/qz-print/commit/d359beeb5d02db651e96c4e8e7756ceff3c3ae6b

**Comment by tresf** [comment]
Confirmed fixed.
