### ISSUE TITLE
qz-print "Detect Printer" button crashes Chrome

### ISSUE THREAD

**Issue by tresf** [qzindustries/qz-print#33]
OS's this bug affects:
- Windows XP 32-bit:  NO
- Windows 7 32-bit:  **YES**
- Windows 8 64-bit:  **YES**

Chrome versions this bug affects:
- Chrome 35.0:  NO
- Chrome 36.0:  **YES**

Similar Chromium bug reports:
- [Issue 366075](https://code.google.com/p/chromium/issues/detail?id=366075)
- [Issue 323447](https://code.google.com/p/chromium/issues/detail?id=323447)

This has been fixed via commit https://github.com/qzindustries/qz-print/commit/b84173c7771857ab0837c651e8b6c8e534a93568 in `1.8.7` which is available to **Premium Customers** via the standard download method.

Demo this fix here:  http://demo.qzindustries.com/ (Should say version `1.8.7`, clear your Java Cache if it reads `1.8.1`)

---

Original Bug Report:

![image](https://cloud.githubusercontent.com/assets/6345473/3649858/5ab1e29a-1116-11e4-925a-1a26da0811dc.png)

Windows version `Windows 8.1 x64`
Chrome version `Version 36.0.1985.125 m` 
Java version `1.7u65`

Steps to reproduce crash:
1.  Close out all instances of Chrome (reboot if unsure)
2.  Navigate to http://qzindustries.com/files/dist_181/sample.html
3.  Click the "Find Printer" button
4.  Chrome hangs and eventually asks to kill "Java Plugin"

**Comment by tresf** [comment]
This bug does **NOT** exist with Chrome `Version 35.0.1916.153 m`.  Seems to be newly introduced with Chrome 36.0.

**Comment by tresf** [comment]
Similar bugs:

https://code.google.com/p/chromium/issues/detail?id=366075

https://code.google.com/p/chromium/issues/detail?id=323447

**Comment by tresf** [comment]
This bug does **NOT** exist on Windows XP 32-bit.  Could **NOT** reproduce.

Windows Version:  `Windows XP 32-bit`
Chrome Version:  `Version 36.0.1985.125 m`
Java Version: `1.7u65`

![image](https://cloud.githubusercontent.com/assets/6345473/3658434/90077fb2-11a3-11e4-8290-62aa511ebdba.png)

**Comment by tresf** [comment]
This bug **DOES** exist on Windows 7 32-bit.

Windows Version: `Windows 7 32-bit`
Chrome Version: `Version 36.0.1985.125 m`
Java Version: `1.7u65`

![image](https://cloud.githubusercontent.com/assets/6345473/3658547/0546d5ba-11a5-11e4-8d29-b44ba24431b9.png)

**Comment by tresf** [comment]
This has been fixed in `1.8.7` which is available to **Premium Customers** via the standard download method.

**Comment by juzerali** [comment]
I hope this release is backward compatible.

**Comment by tresf** [comment]
@juzerali, that would depend on your version, but generally speaking, yes it is backwards compatible.  Many clients are stating this bug does not affect them so only update if needed.

Please test fully prior to rolling-out.
