### ISSUE TITLE
The applet did not load correctly.

### ISSUE THREAD

**Issue by feryardiant** [qzindustries/qz-print#39]
I'd just try to use this applet on Ubuntu 14.04 64bit with Oracle Java 7 update 72 installed, but I got this alert.
![qzprint](https://cloud.githubusercontent.com/assets/508665/4748286/7cab79f2-5a6c-11e4-975a-dfaa9b84898b.png)

I've change my Java Security Level to medium and add the site url to Exception site list but got no luck. anyone can assist me?

Thanks.

**Comment by tresf** [comment]
I just installed Ubuntu 14.04.1 x64, Java 7 Update 72 (via these instructions: http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html)  and it worked first try.

![image](https://cloud.githubusercontent.com/assets/6345473/4774343/5f9f7494-5bac-11e4-8df1-65ca8940f06d.png)

**Comment by feryardiant** [comment]
Your [demo url](http://demo.qzindustries.com/) is fully working
![jzebra-demo](https://cloud.githubusercontent.com/assets/508665/4776198/7f6f840e-5bbf-11e4-869d-001c3d6d8dbb.png)
But not from my local (I just redownload it and doing fresh install)
![jzebra-local](https://cloud.githubusercontent.com/assets/508665/4776222/b6c4ae02-5bbf-11e4-869c-7c5514e4a161.png)

how come? i'm not doing any modifications here. Did I need some special configuration or so?
please help me.

Thanks and regards

**Comment by tresf** [comment]
Please follow the SignerCA instructions in readme.txt.

**Comment by feryardiant** [comment]
as readme.txt said

> - Free versons of the applet are self-signed and will only run when `qz-free.csr` has been added as a "Signer CA" from within the Java Control Panel.
> - If clients do not recieve an update after refreshing the page you can force an update using Java Control Panel, General, View, Remove "QZ Print Plugin"

I do, but seems not working :cry: 
![jzebra](https://cloud.githubusercontent.com/assets/508665/4776717/f68453bc-5bc4-11e4-9f78-1f5bd1d69606.png)

**Comment by tresf** [comment]
That should certainly do it.  Perhaps your webserver does't like JNLP files...

**Comment by feryardiant** [comment]
well, what should I do now? I have no experiences in java programing at all. can you help me?

*\* _still googling some solution_

**Comment by tresf** [comment]
Check to see that the JNLP path is correct.  If you are interested in remote support, you should consider purchasing the premium version.

**Comment by tresf** [comment]
You may also have luck commenting out the try/catch block.  You'll get a better description of the underlying error that way.

**Comment by tresf** [comment]
You also have a tremendously strange root domain "www".  Can you try launching sample.html directly from the Desktop?

**Comment by feryardiant** [comment]
I've planned to purchase your premium version, but for now I just want to learn how it works using free version. Anyway, as you said, I try to edit `try/catch` block

``` js
try { ... }
catch(err) {
    alert("ERROR: \n" + err);
}
```

I got this `alert`
![jzebra](https://cloud.githubusercontent.com/assets/508665/4778154/814b33e8-5bdf-11e4-9426-0f17e9d05af8.png)

also had same alert when I launch `sample.html` file directly from directory

**Comment by tresf** [comment]
Yeah, the LiveConnect error is generally caused by the certificate not being trusted.  Are you sure you properly restarted the browser after adding the certificate?

**Comment by tresf** [comment]
You can also hit "5" in the Java Console to see if there's something else happening.  You'll have to enable it through Configure Java and then restart the browser. It's quite the detailed log, but your exact message should be in there.  If you were using OpenJDK, it would require Firefox be launched from command line to receive any log messages, but I believe the Oracle version has a working console on Ubuntu. 

-Tres

**Comment by tresf** [comment]
I just ran the free version using OpenJDK without any issues.  Perhaps you should do your testing with OpenJDK and if you don't mind requesting an invoice to billing@qzindustries.com, I'll troubleshoot the rest on a grace period.

**Comment by tresf** [comment]
Sorry for the early dismissal of this.  This is in fact a bug.

On Windows 8 x64 Java 7 Update 71, this bug does not occur.  The free version can be run after adding the Self Signed certificate to the Signer CA section of the Configure Java control panel.

On Ubuntu x64 Java 7 Update 72 and Java 8 Update 25, the behavior is different.  The security dialog shows, but the applet is still blocked with the message:  `liveconnect: Security Exception: JavaScript from file:/home/ubuntu/Desktop/dist/sample.html attempted to access a resource it has no rights to.`

This is a completely new warning message.  My instinct is that Oracle is mandating the `Caller-Allowable-Codebase` attribute, which requires a recompile, but I haven't tested that theory yet.

In the mean time, I recommend using OpenJDK until we find a way to resolve this issue.  Sorry about the trouble this bug has caused you.

-Tres

**Comment by tresf** [comment]
The non-custom premium version is also affected by this bug.  If this is any sign of the future, `Caller-Allowable-Codebase` may become mandatory in a future Java release. (We currently build custom versions for our clients which will circumvent this).
