### ISSUE TITLE
Greek chars in printHTML function.

### ISSUE THREAD

**Issue by deliverymanager** [qzindustries/qz-print#42]
Setting the encoding to CP737 doesn't seem to be possible to print Greek chars.
qz.setEncoding("CP737");
Has anyone been able to print Greek or other language than English with the printHTML function?

**Comment by tresf** [comment]
According to stackoverflow, the basic HTML support that comes with Java seems to support HTML 3.2.

I'm not certain as to the validity if this statement, but I believe this limits you to Latin1 for character support, further explained here:

http://www.w3.org/TR/REC-html32.html

I believe this means the closest you will get is to force ISO-8859-1.

**Comment by tresf** [comment]
Closing as this is a bug with Java's HTML interpreter, not our software.  If interested, please try our HTML5 printing feature which will circumvent the issue.
