### ISSUE TITLE
Fedex ZP450 CTP Nothing printing...

### ISSUE THREAD

**Issue by pincusgl** [qzindustries/qz-print#45]
When I click on the "Print ZPL" on the sample htm (in the dist folder) nothing happens

Console:
Dec 11, 2014 6:21:54 PM qz.LogIt log
INFO: Loading BufferedImage
Dec 11, 2014 6:21:54 PM qz.LogIt log
INFO: Dimensions: 256x128
Dec 11, 2014 6:21:54 PM qz.LogIt log
INFO: Initializing Image Fields
Dec 11, 2014 6:21:54 PM qz.LogIt log
INFO: Converting image to monochrome
Dec 11, 2014 6:21:54 PM qz.LogIt log
INFO: Packing bits
Dec 11, 2014 6:21:54 PM qz.LogIt log
WARNING: Tried calling JavaScript function "jzebraDoneAppending" through web browser but it has not been implemented (No such method "jzebraDoneAppending" on JavaScript object)

**Comment by tresf** [comment]
Did you set the printer up as a raw device per: http://qzindustries.com/tutorialrawwin ?

You may want to remove the `qz.appendImage(...)` and `qzDoneAppending()` logic as well and see if it works.

-Tres

**Comment by pincusgl** [comment]
Yes I did set it up as raw exactly per instructions.

The only thing that works is the printHTML()  for  plain html. and the copies.  

Mean while I'm trying to set html printing for the following link the printed but I keep getting "Uncaught TypeError: Cannot read property 'ownerDocument' of undefined" is undefined. when trying to use the html5 canvas.

https://www.uniprouniforms.com/new/system/java/qz-print/dist/sample.html

I wanted to ask you, How much would you charge me to get me an html page where I should be able to print regular docs to the regular printer and shipping lables to zebra from the same page (I'm almost willing pay to pay anything...)

Thanks, and if you help me I owe you the world (plus any fees...)

Pincus G
UniPro International

**Comment by tresf** [comment]
`#up_uniforms_sec` looks like an ID tag, but you're using it as a class name (generally would be selected by jQuery as `.up_uniforms_sec` <--- notice the dot instead of hash mark).  I'm not sure you have a valid selector around it, which is probably why html2canvas is throwing that error (it can't find the element because it doesn't exist).

But HTML5 is a very slippery slope.  I'd recommend you first become comfortable with the ZPL logic.  Did you have a chance to remove the `qz.appendImage(..)` logic like I had already proposed?  The printer you linked appears to support ZPL, so its probably worth sending it a "Hello world" for starters and going from there.

-Tres

**Comment by pincusgl** [comment]
Hi, And Good Morning,

I was pretty serious when I said I'm willing to pay and willing to "Pre-pay" through credit card or pay-pal for your time if you are able to log-in to my computer (log-me-in, or any other method you might have..).

To help me figure out what is going on, 

I have an online system where I print Picking tickets & Packing lists for our warehouse, and I want to bypass the print dialog (so they print directly to the printer..).

then on the same computer/machine they will have a FedEx/web terminal (which I'm in the process of developing.. ) where they will print the shipping labels and get the weight of the packages everyt8ng from the same screen.

Please let me know if the above is possible for I am willing to pre-pay for as much time you think it might take.  (what it might take you a few minute.. might take me a week to figure out.. 

Please help, Thanks again...

Pincus G
UniPro International

**Comment by tresf** [comment]
> I was pretty serious when I said I'm willing to pay and willing to "Pre-pay" through credit card or pay-pal for your time if you are able to log-in to my computer (log-me-in, or any other method you might have..).

This is standard support that we offer for existing clients and prospecting clients.  Please contact me at support@qzindustries.com and we can setup a time.

**Comment by tresf** [comment]
Closing as Pincus and QZ resolved our issues temporarily via https://github.com/qzindustries/qz-print/commit/af111a8367b75dc2c2a92fdf07ae01dc2c95f1b2.
