### ISSUE TITLE
Applet in HTML5?!

### ISSUE THREAD

**Issue by yanko-belov** [qzindustries/qz-print#46]
The people from W3 advice:

**The <applet> tag is not supported in HTML5. Use the <object> tag instead.**

Then is it wise to use applet to run qz-print plugin ot HTML5 web app?

**Comment by tresf** [comment]
`<object>` tags aren't as reliable.  If you are unsure of which to use, Oracle recommends using the `deployJava` function, which is bundled as part of `sample.html`.

**Comment by tresf** [comment]
Furthermore, the future of qz will use HTML5 websockets, so we have a plan to move away from applet tags eventually.

**Comment by yanko-belov** [comment]
Thanks, this definitely helps a lot.
