### ISSUE TITLE
HTML multi page printing

### ISSUE THREAD

**Issue by ghost** [qzindustries/qz-print#47]
I have ftl template with multiple pages, when I give print qz printing only the first page, other pages got trimmed, please help me with this issue.

**Comment by tresf** [comment]
We currently do not support multiple page prints via HTML.  I am sorry for this inconvenience.  It is on our radar, but we do not have a timeline for implementing this feature.

**Comment by tresf** [comment]
Multi-page printing is on the radar for this summer.  Closing this out as we'll be tracking this at our new repository, once started:  https://github.com/qzind/qz-print
