### ISSUE TITLE
PDF from Base64 string to PostScript printer.

### ISSUE THREAD

**Issue by Ugzuzg** [qzindustries/qz-print#49]
Pass base64 of PDF file to applet to print it.
https://gist.github.com/Ugzuzg/b79147f2f58c02760d6b

**Comment by tresf** [comment]
ByteUtilities.readBinaryFile already does that automatically per:

https://github.com/qzindustries/qz-print/blob/1.8.0/qz-print/src/qz/ByteUtilities.java#L255
