### ISSUE TITLE
Print plugin is NOT loaded properly!

### ISSUE THREAD

**Issue by kw-pr** [qzindustries/qz-print#54]
If I load the sample.html in Chrome 40 it does not work. If I click on any button an alert is shown: "Print plugin is NOT loaded properly!". Background stays yellow.

If I load the same page in IE 11 it works. Background turns gray and I can print.

I did add the certificate and allowed the plugin on this page.

Maybe someone might know what's wrong...

**Comment by tresf** [comment]
If you are on a 64-bit workstation, Chrome will require the 32-bit version of Java installed whereas IE 11 will require the 64-bit version of Java installed.

-Tres

**Comment by kw-pr** [comment]
ok, thanks a lot
