### ISSUE TITLE
WARNING: PostScript data can not be sent to a raw printer.

### ISSUE THREAD

**Issue by tresf** [qzindustries/qz-print#7]
Using version 1.9.9.1 the message `WARNING: PostScript/RTF data can not be sent to a raw printer` is displayed for most printers.  Example:  "XPS Document Writer".

```
Feb 18, 2014 9:21:12 PM qz.LogIt log
INFO: Applet Started
Feb 18, 2014 9:21:12 PM qz.LogIt log
INFO: PrintSpooler started
Feb 18, 2014 9:21:12 PM qz.LogIt log
INFO: Succesfully called JavaScript function "qzReady(...)"...
Feb 18, 2014 9:21:13 PM qz.LogIt log
INFO: Found printer "Microsoft XPS Document Writer".
Feb 18, 2014 9:21:16 PM qz.LogIt log
INFO: Print Successful
Feb 18, 2014 9:21:16 PM qz.LogIt log
WARNING: RTF data can not be sent to a raw printer.
Feb 18, 2014 9:21:18 PM qz.LogIt log
INFO: Succesfully called JavaScript function "qzDonePrinting(...)"...

```

**Comment by tresf** [comment]
An update, after examing `PrintSpooler.java`, I don't believe querying the PrintService capabilities (i.e. PostScript support) is a reliable indicator of printer capabilities.

For example, some users go against the recommendation to use a Generic/Text driver and use the Zebra ZDesigner driver instead.  Although this shouldn't necessarily work, it seems the new drivers supplied by Zebra (for example) can accept either format. A second example is the XPS Document writer, which seems to want a non-PostScript 2D docflavor (perhaps PCL?).  So testing with XPS Document Writer stopped working with release 1.9.9.1 because it tells Java (perhaps incorrectly) that it does not support PostScript.

Although adding additional docflavors could help this idea of PrintService capability "auto-detection" of raw vs. PS, obtaining the capabilities of the printer is great for WARNING messages, but I'm not sure it should determine how the applet behaves.  I would instead recommend setting a flag based on which print data is supplied.  i.e. appendRTF() or appendPDF can assume PostScript whereas append() can assume Raw, etc.

A snippet of the existing logic, which should be changed:

```
if(ps.isDocFlavorSupported(DocFlavor.INPUT_STREAM.POSTSCRIPT)) {
    printer = (PSPrinter)new PSPrinter();
}
else {
    printer = (RawPrinter)new RawPrinter();
}
```

**Comment by myrridin** [comment]
This should be addressed for ps printing to printers that don't report ps support. Commit here: https://github.com/qzindustries/qz-print/commit/b54c1718dfc7ae538196e6e0453977cf21416d52

I tested this on my hardware printer which suffered the same bug, and the print sent successfully.
